apiVersion: v1
kind: Namespace
metadata:
  name: pet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pett-deployment
  namespace: pet
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: 783911693980.dkr.ecr.ap-south-1.amazonaws.com/petclinic:number
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pet-svc
  namespace: pet
spec:
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer